version: '3'

services:
  to-webp:
    build: ./
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.to-webp.entrypoints=websecure
      - traefik.http.routers.to-webp.rule=Host(`to-webp.${DOMAIN:-localhost}`)

networks:
  traefik:
    external: true
