version: '3'

services:
  to-webp:
    build: ./
    restart: unless-stopped
    tty: true
    volumes:
      - ~/shared:/shared
    expose:
      - 3000
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.to-webp.entrypoints=websecure
      - traefik.http.routers.to-webp.rule=Host(`to-webp.${DOMAIN:-localhost}`)

networks:
  traefik:
    external: true
# version: '3'

# services:
#   app:
#     image: node:16
#     container_name: foo
#     working_dir: /var/www/foo
#     user: node
#     tty: true
#     ports:
#       - 3000:3000
#     volumes:
#       - ./:/var/www/foo
